apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db1
spec:
  ports:
    - port: 5432
  selector:
    app: db1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db1
spec:
  selector:
    matchLabels:
      app: db1
  template:
    metadata:
      labels:
        app: db1
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: curso_springboot
            - name: POSTGRES_USER
              value: devdb
            - name: POSTGRES_PASSWORD
              value: a1b2c3d4
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db1-storage
      volumes:
        - name: db1-storage
          persistentVolumeClaim:
            claimName: db1-pvc